version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data/db

  redis:
    image: redis:latest
    ports:
      - 6379:6379
