version: '3'
services:
  app:
      container_name: app
      build: .
      command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
      volumes:
        - .:/app
      ports:
        - 8001:8000
      restart: always

  redis:
    image: redis:6.2-alpine
    # image: redis:latest
    ports:
      - 6379:6379 

  # fastapi:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - mongodb
  #     # - redis

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data/db

  # redis:
  #   image: redis:6.2-alpine
  #   # image: redis:latest
  #   # ports:
  #     # - 6379:6379
